/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.consultadesintomas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 05136425016
 */
public class CadastroDoenca extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDoenca
     */
    public CadastroDoenca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnCadastroDeDoenca = new javax.swing.JPanel();
        JlbTitulo = new javax.swing.JLabel();
        txtDoenca = new javax.swing.JTextField();
        JlbNome = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnCadastrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlbTitulo.setText("Cadastro De Doenças");

        JlbNome.setText("Digite o nome da doença");

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnCadastrar1.setText("Cadastrar");
        BtnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnCadastroDeDoencaLayout = new javax.swing.GroupLayout(JpnCadastroDeDoenca);
        JpnCadastroDeDoenca.setLayout(JpnCadastroDeDoencaLayout);
        JpnCadastroDeDoencaLayout.setHorizontalGroup(
            JpnCadastroDeDoencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnCadastroDeDoencaLayout.createSequentialGroup()
                .addGroup(JpnCadastroDeDoencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnCadastroDeDoencaLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(JlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpnCadastroDeDoencaLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(JpnCadastroDeDoencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlbNome)
                            .addGroup(JpnCadastroDeDoencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(JpnCadastroDeDoencaLayout.createSequentialGroup()
                                    .addComponent(BtnCadastrar1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnCancelar))
                                .addComponent(txtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        JpnCadastroDeDoencaLayout.setVerticalGroup(
            JpnCadastroDeDoencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnCadastroDeDoencaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(JlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JlbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(JpnCadastroDeDoencaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar1)
                    .addComponent(BtnCancelar))
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnCadastroDeDoenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnCadastroDeDoenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BtnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrar1ActionPerformed
 
        String descricaoDoenca = txtDoenca.getText();
        cadastrarDoenca(descricaoDoenca);
        txtDoenca.setText("");

        
        
    }//GEN-LAST:event_BtnCadastrar1ActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    
    
    private Connection conectarBanco() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/consultaSintomas";
        String usuario = "root";
        String senha = "root";
        return DriverManager.getConnection(url, usuario, senha);
    }
    
    
 private void cadastrarDoenca(String descricaoDoenca) {
        try {
            Connection conexao = conectarBanco();

            // Inserir a doença na tabela DOENCAS
            String insertDoencaSQL = "INSERT INTO DOENCAS (DOENCA_DESCRICAO) VALUES (?)";
            PreparedStatement pstmtDoenca = conexao.prepareStatement(insertDoencaSQL);

            pstmtDoenca.setString(1, descricaoDoenca);

            int rowsAffected = pstmtDoenca.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Doença cadastrada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma doença foi cadastrada.");
            }

            pstmtDoenca.close();
            conexao.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar doença: " + e.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDoenca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar1;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel JlbNome;
    private javax.swing.JLabel JlbTitulo;
    private javax.swing.JPanel JpnCadastroDeDoenca;
    private javax.swing.JTextField txtDoenca;
    // End of variables declaration//GEN-END:variables
}
